import { PDFDocument, StandardFonts } from 'pdf-lib';
import sharp from 'sharp';
const doc = await PDFDocument.create();
doc.setProducer('probe-producer');
doc.setCreator('probe-creator');
doc.setCreationDate(new Date('2024-03-04T10:11:12Z'));
const font = await doc.embedFont(StandardFonts.Helvetica);
doc.addPage([420, 595]).drawText('Hola prova 123', { x: 40, y: 500, size: 24, font });
const bytes = await doc.save();
const back = await PDFDocument.load(bytes, { updateMetadata: false });
console.log('producer', back.getProducer(), '| creator', back.getCreator(), '| created', back.getCreationDate(), '| mod', back.getModificationDate(), '| pages', back.getPageCount());
console.log('heif out?', sharp.format.heif?.output, 'jp2', !!sharp.format.jp2);
console.log('formats', Object.keys(sharp.format).join(','));
