/**
 * Synthetic documents for tests. Every vendor, community and person is invented; owners appear
 * only as unit labels. Identifiers are valid by construction so validators can be exercised.
 */
import { cccToIban } from '../../ids/iban.ts';
import { CIF_CONTROL_LETTERS, cifControlDigit } from '../../ids/nif.ts';
import type { Acta } from '../schemas/acta.ts';
import type { Certificacion } from '../schemas/certificacion.ts';
import type { EvidenceItem } from '../schemas/common.ts';
import type { Contrato } from '../schemas/contrato.ts';
import type { Derrama } from '../schemas/derrama.ts';
import type { Extracto } from '../schemas/extracto.ts';
import type { Factura } from '../schemas/factura.ts';
import type { Liquidacion } from '../schemas/liquidacion.ts';
import type { PaginaBatch } from '../schemas/pagina.ts';
import type { Presupuesto } from '../schemas/presupuesto.ts';

/** Valid CIF for an entity letter and 7 digits (digit control for A/B/H, letter for others). */
export function makeCif(entity: string, digits7: string): string {
  const c = cifControlDigit(digits7);
  const control = 'ABEH'.includes(entity) ? String(c) : CIF_CONTROL_LETTERS.charAt(c);
  return `${entity}${digits7}${control}`;
}

export const CIF_VENDOR = makeCif('B', '6543210'); // Instal·lacions Exemple S.L.
export const CIF_LIFT = makeCif('A', '1122334'); // Ascensors Exemple S.A.
export const CIF_CLEAN = makeCif('B', '9988776'); // Neteges Exemple S.L.
export const CIF_ADMIN = makeCif('B', '5556667'); // Administracions Exemple S.L.
export const NIF_COMMUNITY = makeCif('H', '6677889'); // Comunitat de Propietaris Carrer Exemple 25
export const IBAN_COMMUNITY = cccToIban('2100', '0418', '0200051332');
export const IBAN_VENDOR = cccToIban('0081', '0057', '0001234567');

const ev = (field_path: string, page_index: number, quote: string, confidence = 0.96, bbox: number[] | null = [100, 200, 300, 230]): EvidenceItem => ({
  field_path,
  page_index,
  bbox,
  quote,
  confidence,
});

export const facturaFixture: Factura = {
  doc_type_confirmed: 'factura',
  serie: null,
  numero: 'F-2024/017',
  fecha_expedicion: '2024-03-15',
  fecha_operacion: null,
  emisor: {
    nombre: 'Instal·lacions Exemple S.L.',
    nif: CIF_VENDOR,
    domicilio: 'Carrer de la Mostra 12, baixos',
    cp: '08015',
    municipio: 'Barcelona',
    email: 'admin@instalacions-exemple.example',
    telefono: '930 000 000',
  },
  destinatario: {
    nombre: 'Comunitat de Propietaris Carrer Exemple 25',
    nif: NIF_COMMUNITY,
    domicilio: 'Carrer Exemple 25, 08015 Barcelona',
  },
  lineas: [
    {
      orden: 1,
      codigo: null,
      descripcion: "Substitució porta d'accés a l'edifici",
      cantidad: 1,
      unidad: 'ud',
      precio_unitario: 2400,
      descuento_pct: null,
      base: 2400,
      tipo_iva_pct: 10,
      cuota_iva: 240,
      total_linea: 2640,
      es_manuscrito: false,
      es_partida_alzada: false,
      element_scope: 'common',
      unit_hint: null,
    },
    {
      orden: 2,
      codigo: null,
      descripcion: "Mà d'obra instal·lació",
      cantidad: 8,
      unidad: 'h',
      precio_unitario: 45,
      descuento_pct: null,
      base: 360,
      tipo_iva_pct: 10,
      cuota_iva: 36,
      total_linea: 396,
      es_manuscrito: false,
      es_partida_alzada: false,
      element_scope: 'common',
      unit_hint: null,
    },
    {
      orden: 3,
      codigo: 'ACC-01',
      descripcion: 'Ferramenta i accessoris',
      cantidad: 1,
      unidad: 'ud',
      precio_unitario: 180,
      descuento_pct: null,
      base: 180,
      tipo_iva_pct: 21,
      cuota_iva: 37.8,
      total_linea: 217.8,
      es_manuscrito: false,
      es_partida_alzada: false,
      element_scope: 'unknown',
      unit_hint: null,
    },
  ],
  resumen_iva: [
    { base: 2760, tipo_pct: 10, cuota: 276 },
    { base: 180, tipo_pct: 21, cuota: 37.8 },
  ],
  base_imponible_total: 2940,
  iva_total: 313.8,
  retencion_irpf: null,
  suplidos: null,
  total_factura: 3253.8,
  forma_pago: 'transferencia',
  iban_mostrado: IBAN_VENDOR,
  vencimiento: '2024-04-15',
  referencia_presupuesto_o_obra: 'PRESSUPOST 2024-003',
  rectifica_factura: null,
  menciones: {
    exenta: false,
    inversion_sujeto_pasivo: false,
    criterio_caja: false,
    materiales_40pct: true,
    verifactu_qr_presente: false,
  },
  sello_o_firma_presente: true,
  anotaciones_manuscritas: [{ texto: 'pagat 20/4', page_index: 0, bbox: [900, 1400, 1100, 1440] }],
  evidence: [
    ev('numero', 0, 'F-2024/017'),
    ev('fecha_expedicion', 0, '15/03/2024'),
    ev('emisor.nif', 0, CIF_VENDOR),
    ev('destinatario.nif', 0, NIF_COMMUNITY),
    ev('lineas[0].base', 0, '2.400,00'),
    ev('lineas[1].base', 0, '360,00'),
    ev('lineas[2].base', 0, '180,00'),
    ev('resumen_iva[0].base', 0, '2.760,00'),
    ev('resumen_iva[1].base', 0, '180,00'),
    ev('base_imponible_total', 0, '2.940,00 €'),
    ev('iva_total', 0, '313,80 €'),
    ev('total_factura', 0, '3.253,80 €', 0.99, [820, 1300, 1010, 1332]),
    ev('iban_mostrado', 0, IBAN_VENDOR.replace(/(.{4})/g, '$1 ').trim()),
  ],
  self_checks: { lineas_suman_base: true, base_mas_iva_es_total: true, discrepancia_eur: null },
  idioma: 'ca',
  notes: null,
};

export const extractoFixture: Extracto = {
  doc_type_confirmed: 'extracto_bancario',
  banco: 'CaixaBank',
  iban_o_cuenta_mostrada: IBAN_COMMUNITY,
  titular: 'CDAD PROP CARRER EXEMPLE 25',
  titular_es_persona_fisica: false,
  periodo: { desde: '2024-05-01', hasta: '2024-05-31' },
  fecha_emision: '2024-06-01',
  moneda: 'EUR',
  paginacion: { pagina: 1, de: 1 },
  saldo_inicial: 12500.4,
  saldo_final: 9114.6,
  movimientos: [
    {
      fecha_operacion: '2024-05-02',
      fecha_valor: '2024-05-02',
      concepto: 'REBUT COMUNITAT 3º 2ª [persona]',
      importe: 60,
      saldo_tras: 12560.4,
      contraparte_nombre: null,
      contraparte_es_persona_fisica: true,
      contraparte_iban: null,
      referencia: null,
      unit_hint: '3º 2ª',
      page_index: 0,
      bbox: [60, 400, 1500, 430],
    },
    {
      fecha_operacion: '2024-05-03',
      fecha_valor: '2024-05-03',
      concepto: 'TRANSFERENCIA A INSTAL·LACIONS EXEMPLE SL FRA F-2024/017',
      importe: -3253.8,
      saldo_tras: 9306.6,
      contraparte_nombre: 'INSTAL·LACIONS EXEMPLE SL',
      contraparte_es_persona_fisica: false,
      contraparte_iban: IBAN_VENDOR,
      referencia: 'F-2024/017',
      unit_hint: null,
      page_index: 0,
      bbox: [60, 440, 1500, 470],
    },
    {
      fecha_operacion: '2024-05-10',
      fecha_valor: null,
      concepto: 'COMISSIO MANTENIMENT COMPTE',
      importe: -12,
      saldo_tras: 9294.6,
      contraparte_nombre: null,
      contraparte_es_persona_fisica: false,
      contraparte_iban: null,
      referencia: null,
      unit_hint: null,
      page_index: 0,
      bbox: [60, 480, 1500, 510],
    },
    {
      fecha_operacion: '2024-05-20',
      fecha_valor: '2024-05-20',
      concepto: 'REBUT ADMINISTRACIONS EXEMPLE SL HONORARIS MAIG',
      importe: -180,
      saldo_tras: 9114.6,
      contraparte_nombre: 'ADMINISTRACIONS EXEMPLE SL',
      contraparte_es_persona_fisica: false,
      contraparte_iban: null,
      referencia: 'MANDATO 000123',
      unit_hint: null,
      page_index: 0,
      bbox: [60, 520, 1500, 550],
    },
  ],
  anotaciones_manuscritas: [],
  evidence: [
    ev('saldo_inicial', 0, '12.500,40'),
    ev('saldo_final', 0, '9.114,60'),
    ev('iban_o_cuenta_mostrada', 0, IBAN_COMMUNITY),
    ev('periodo.desde', 0, '01/05/2024'),
    ev('periodo.hasta', 0, '31/05/2024'),
  ],
  self_checks: {
    saldo_inicial_mas_movimientos_es_saldo_final: true,
    saldos_intermedios_consistentes: true,
    discrepancia_eur: null,
  },
  idioma: 'ca',
  notes: null,
};

export const certificacionFixture: Certificacion = {
  doc_type_confirmed: 'certificacion_obra',
  numero_certificacion: '3',
  fecha: '2025-02-28',
  periodo: { desde: '2025-02-01', hasta: '2025-02-28' },
  obra: "Instal·lació d'ascensor Carrer Exemple 25",
  contratista: { nombre: 'Ascensors Exemple S.A.', nif: CIF_LIFT, domicilio: 'Polígon Mostra, nau 4' },
  propiedad: { nombre: 'Comunitat de Propietaris Carrer Exemple 25', nif: NIF_COMMUNITY, domicilio: null },
  importe_contrato: 42000,
  partidas: [
    { orden: 1, codigo: '01.01', descripcion: 'Obra civil fossat i buit', unidad: 'PA', cantidad_contrato: 1, precio_unitario: 15000, importe_contrato: 15000, a_origen: 15000, anterior: 9000, actual: 6000, pct_ejecutado: 100, es_extra: false },
    { orden: 2, codigo: '02.01', descripcion: 'Subministrament maquinària', unidad: 'PA', cantidad_contrato: 1, precio_unitario: 27000, importe_contrato: 27000, a_origen: 4000, anterior: 1500, actual: 2500, pct_ejecutado: 14.81, es_extra: false },
  ],
  totales: { a_origen: 19000, anterior: 10500, actual: 8500 },
  retencion_garantia: { pct: 5, importe: 425 },
  base_certificacion: 8500,
  iva: { pct: 10, importe: 850 },
  total_certificacion: 8925,
  firmas: { contratista: true, direccion_facultativa: true, propiedad: false },
  firmas_roles: ['gerent', 'arquitecte tècnic'],
  anotaciones_manuscritas: [],
  evidence: [ev('totales.actual', 0, '8.500,00'), ev('total_certificacion', 0, '8.925,00'), ev('contratista.nif', 0, CIF_LIFT)],
  self_checks: { actual_es_origen_menos_anterior: true, partidas_suman_totales: true, discrepancia_eur: null },
  idioma: 'ca',
  notes: null,
};

export const contratoFixture: Contrato = {
  doc_type_confirmed: 'contrato_ascensor',
  kind: 'ascensor_instalacion',
  titulo: "Contracte d'instal·lació d'ascensor",
  fecha_firma: '2024-09-10',
  lugar_firma: 'Barcelona',
  partes: [
    { rol: 'contratista', nombre: 'Ascensors Exemple S.A.', nif: CIF_LIFT, representante_rol: 'apoderat', domicilio: 'Polígon Mostra, nau 4' },
    { rol: 'comunidad', nombre: 'Comunitat de Propietaris Carrer Exemple 25', nif: NIF_COMMUNITY, representante_rol: 'president', domicilio: 'Carrer Exemple 25' },
  ],
  objeto: "Subministrament i instal·lació d'un ascensor de 6 parades",
  referencia_presupuesto: 'OF-2024-118',
  precio: { sin_iva: 48000, iva_pct: 10, con_iva: 52800 },
  es_precio_cerrado: true,
  calendario_pagos: [
    { hito: 'a la signatura', pct: 30, importe: 15840, condicion: null, es_anticipo: true },
    { hito: 'inici muntatge', pct: 40, importe: 21120, condicion: 'a la recepció del material a obra', es_anticipo: false },
    { hito: 'posada en marxa', pct: 30, importe: 15840, condicion: 'acta de recepció signada', es_anticipo: false },
  ],
  plazo: { inicio: 'a la concessió de la llicència', duracion: '16 setmanes', fin_previsto: null },
  penalizaciones: [{ concepto: 'retard en la posada en marxa', importe_o_pct: '0,1 % per dia', texto: 'penalització del 0,1 % del preu per dia natural de retard' }],
  retencion_garantia: { pct: 5, importe: 2400, plazo_devolucion: '12 mesos des de la recepció' },
  garantia_meses: 24,
  permanencia_meses: null,
  revision_precios: null,
  licencia_a_cargo_de: 'comunidad',
  prl_cae_mencion: true,
  firmas: [
    { rol: 'president', fecha: '2024-09-10', presente: true },
    { rol: 'apoderat', fecha: '2024-09-10', presente: true },
  ],
  elevator_spec: { marca_modelo: 'Exemple E-600', paradas: 6, carga_kg: 450, velocidad: '1 m/s', mantenimiento_incluido_meses: 12, precio_mantenimiento_anual: 1500 },
  prestamo_spec: null,
  clausulas_relevantes: [{ tema: 'pagos', resumen: '30 % a la signatura, 40 % a l\'inici del muntatge, 30 % a la posada en marxa', page_index: 1 }],
  evidence: [ev('precio.con_iva', 1, '52.800,00 €'), ev('precio.sin_iva', 1, '48.000,00 €'), ev('partes[0].nif', 0, CIF_LIFT)],
  self_checks: { sin_iva_mas_iva_es_con_iva: true, calendario_suma_100pct: true, discrepancia_eur: null },
  idioma: 'ca',
  notes: null,
};

export const liquidacionFixture: Liquidacion = {
  doc_type_confirmed: 'liquidacion_anual',
  ejercicio: 2024,
  periodo: { desde: '2024-01-01', hasta: '2024-12-31' },
  administrador_nombre: 'Administracions Exemple S.L.',
  administrador_es_persona_fisica: false,
  comunidad: { nombre: 'Comunitat de Propietaris Carrer Exemple 25', nif: NIF_COMMUNITY },
  criterio_contable: 'cash',
  ingresos: [
    { concepto: 'Quotes ordinàries', importe: 6720, presupuestado: 6720, capitulo: 'Ingressos', page_index: 0 },
    { concepto: 'Derrama obres', importe: 10800, presupuestado: 10800, capitulo: 'Ingressos', page_index: 0 },
  ],
  gastos: [
    { concepto: 'Neteja escala', proveedor: 'Neteges Exemple S.L.', importe: 2400, presupuestado: 2400, capitulo: 'Serveis', page_index: 0 },
    { concepto: 'Assegurança', proveedor: null, importe: 900, presupuestado: 900, capitulo: 'Serveis', page_index: 0 },
    { concepto: 'Honoraris administració', proveedor: 'Administracions Exemple S.L.', importe: 1800, presupuestado: 1800, capitulo: 'Serveis', page_index: 0 },
    { concepto: 'Subministrament elèctric', proveedor: null, importe: 780, presupuestado: 800, capitulo: 'Subministraments', page_index: 0 },
    { concepto: 'Manteniment ascensor', proveedor: 'Ascensors Exemple S.A.', importe: 1500, presupuestado: 1500, capitulo: 'Serveis', page_index: 1 },
    { concepto: 'Obres porta accés', proveedor: 'Instal·lacions Exemple S.L.', importe: 9000, presupuestado: null, capitulo: 'Obres', page_index: 1 },
  ],
  totales: { total_ingresos: 17520, total_gastos: 16380, resultado: 1140 },
  saldos: { inicial: 3200, final: 4340, en_banco: 4340, en_caja: 0 },
  fondo_reserva: { inicial: 800, dotacion: 336, disposiciones: 0, final: 1136 },
  saldo_en_poder_administrador: null,
  pendientes: { facturas_pendientes_pago: 0, retenciones_pendientes: null, acreedores_total: 0, deudores_total: 120 },
  deudores: [{ entidad_label: '4t 1a', importe: 120 }],
  acreedores: [],
  derramas: [{ concepto: 'Derrama obres 60 €/mes', importe_total: 10800, recaudado: 10680, aplicado: 9000, pendiente: 120 }],
  cuotas_por_unidad: [
    { entidad_label: 'Pral 1a', coeficiente_pct: 6.5, cuota_ordinaria: 36.4, cuota_extraordinaria: 60, deuda_pendiente: 0 },
    { entidad_label: '1r 1a', coeficiente_pct: 7.2, cuota_ordinaria: 40.32, cuota_extraordinaria: 60, deuda_pendiente: 0 },
    { entidad_label: '4t 1a', coeficiente_pct: 5.9, cuota_ordinaria: 33.04, cuota_extraordinaria: 60, deuda_pendiente: 120 },
  ],
  aprobada_en_junta: null,
  anotaciones_manuscritas: [],
  evidence: [ev('totales.total_gastos', 1, '16.380,00'), ev('totales.total_ingresos', 1, '17.520,00'), ev('comunidad.nif', 0, NIF_COMMUNITY)],
  self_checks: {
    ingresos_suman_total: true,
    gastos_suman_total: true,
    resultado_es_ingresos_menos_gastos: true,
    saldo_inicial_mas_resultado_es_final: true,
    fondo_reserva_cuadra: true,
    discrepancia_eur: null,
  },
  idioma: 'ca',
  notes: null,
};

export const actaFixture: Acta = {
  doc_type_confirmed: 'acta',
  tipo: 'ordinaria',
  comunidad: { nombre: 'Comunitat de Propietaris Carrer Exemple 25', nif: NIF_COMMUNITY },
  fecha: '2023-03-14',
  hora: '19:30',
  lugar: "Vestíbul de l'edifici",
  fecha_convocatoria: '2023-03-01',
  convocada_por_rol: 'president',
  segunda_convocatoria: true,
  asistentes: [
    { entidad_label: 'Pral 1a', presente_o_representado: 'presente', coeficiente_pct: 6.5 },
    { entidad_label: '1r 1a', presente_o_representado: 'presente', coeficiente_pct: 7.2 },
    { entidad_label: '2n 2a', presente_o_representado: 'representado', coeficiente_pct: 5.9 },
    { entidad_label: '3r 1a', presente_o_representado: 'presente', coeficiente_pct: 8.1 },
    { entidad_label: '4t 2a', presente_o_representado: 'presente', coeficiente_pct: 6.3 },
  ],
  quorum_pct: 34,
  quorum_unidades: 5,
  orden_del_dia: ['Aprovació dels comptes 2022', "Instal·lació d'ascensor: pressupostos", 'Derrama per a les obres', 'Precs i preguntes'],
  acuerdos: [
    {
      punto: '1',
      titulo: 'Aprovació dels comptes 2022',
      texto_literal: "S'aproven per unanimitat els comptes de l'exercici 2022 presentats per l'administrador.",
      resultado: 'aprobado',
      votos: null,
      unanimidad_declarada: true,
      coeficientes_favor_pct: null,
      importes_mencionados: [],
      proveedor_mencionado: null,
      delegacion: null,
      plazo: null,
      page_index: 0,
    },
    {
      punto: '2',
      titulo: "Instal·lació d'ascensor",
      texto_literal: "S'aprova contractar la instal·lació de l'ascensor amb Ascensors Exemple S.A. per un import de 52.800,00 € IVA inclòs i es faculta el [president] per signar el contracte.",
      resultado: 'aprobado',
      votos: { favor: 5, contra: 0, abstencion: 0 },
      unanimidad_declarada: false,
      coeficientes_favor_pct: 34,
      importes_mencionados: [{ concepto: "instal·lació de l'ascensor IVA inclòs", importe: 52800 }],
      proveedor_mencionado: 'Ascensors Exemple S.A.',
      delegacion: { a_quien_rol: 'president', alcance: 'signar el contracte', limite_importe: null },
      plazo: null,
      page_index: 1,
    },
    {
      punto: '3',
      titulo: 'Derrama',
      texto_literal: "S'aprova una derrama de 60 € mensuals per entitat durant 15 mesos a partir de l'abril de 2023.",
      resultado: 'aprobado',
      votos: { favor: 4, contra: 1, abstencion: 0 },
      unanimidad_declarada: false,
      coeficientes_favor_pct: 28.1,
      importes_mencionados: [{ concepto: 'derrama mensual per entitat', importe: 60 }],
      proveedor_mencionado: null,
      delegacion: null,
      plazo: '15 mesos',
      page_index: 1,
    },
  ],
  cargos_elegidos: [{ cargo: 'president', entidad_label: '3r 1a' }],
  cuentas_aprobadas: true,
  presupuesto_aprobado: 6720,
  derramas_aprobadas: [{ objeto: 'obres ascensor', importe_total: null, importe_por_unidad: 60, criterio: 'parts iguals', periodicidad: 'mensual', inicio: 'abril 2023' }],
  firmas: { presidente: true, secretario: true, administrador: false },
  fecha_cierre_acta: '2023-03-16',
  anotaciones_manuscritas: [],
  evidence: [ev('acuerdos[1].importes_mencionados[0].importe', 1, '52.800,00 €'), ev('quorum_pct', 0, '34,00 %'), ev('fecha', 0, '14 de març de 2023')],
  self_checks: { coeficientes_asistentes_le_100: true, quorum_coincide_con_asistentes: true, discrepancia_eur: null },
  idioma: 'ca',
  notes: null,
};

export const derramaFixture: Derrama = {
  doc_type_confirmed: 'aviso_derrama',
  fecha: '2023-03-25',
  emisor_rol: 'administrador',
  comunidad: { nombre: 'Comunitat de Propietaris Carrer Exemple 25', nif: NIF_COMMUNITY },
  junta_que_aprueba: 'Junta ordinària de 14/03/2023',
  objeto: 'Obres ascensor',
  importe_total: 2160,
  criterio_reparto: 'partes_iguales',
  periodicidad: 'mensual',
  numero_plazos: 12,
  cuotas: [
    { entidad_label: 'Pral 1a', coeficiente_pct: 6.5, importe: 720, plazos: [{ fecha: '2023-04-01', importe: 60 }, { fecha: '2023-05-01', importe: 60 }] },
    { entidad_label: '1r 1a', coeficiente_pct: 7.2, importe: 720, plazos: [] },
    { entidad_label: '4t 1a', coeficiente_pct: 5.9, importe: 720, plazos: [] },
  ],
  cuenta_destino_iban: IBAN_COMMUNITY,
  recibo: null,
  anotaciones_manuscritas: [],
  evidence: [ev('importe_total', 0, '2.160,00'), ev('cuenta_destino_iban', 0, IBAN_COMMUNITY)],
  self_checks: { cuotas_suman_total: true, discrepancia_eur: null },
  idioma: 'ca',
  notes: 'Only two instalments printed for Pral 1a; the notice lists 12 months in the text.',
};

export const presupuestoFixture: Presupuesto = {
  doc_type_confirmed: 'presupuesto',
  numero_presupuesto: '2024-003',
  fecha: '2024-02-20',
  emisor: { nombre: 'Instal·lacions Exemple S.L.', nif: CIF_VENDOR, domicilio: 'Carrer de la Mostra 12' },
  destinatario: { nombre: 'Comunitat de Propietaris Carrer Exemple 25', nif: NIF_COMMUNITY, domicilio: null },
  objeto: "Substitució de la porta d'accés",
  referencia_obra: 'Carrer Exemple 25',
  capitulos: [
    {
      codigo: '01',
      titulo: 'Desmuntatge',
      partidas: [
        { orden: 1, codigo: '01.01', descripcion: 'Desmuntatge porta existent', cantidad: 1, unidad: 'ud', precio_unitario: 1200, importe: 1200, es_manuscrito: false, es_partida_alzada: false, element_scope: 'common', unit_hint: null },
        { orden: 2, codigo: '01.02', descripcion: 'Retirada de runa a abocador', cantidad: 1, unidad: 'PA', precio_unitario: null, importe: 800, es_manuscrito: false, es_partida_alzada: true, element_scope: 'common', unit_hint: null },
      ],
      importe_capitulo: 2000,
    },
    {
      codigo: '02',
      titulo: 'Porta nova',
      partidas: [
        { orden: 1, codigo: '02.01', descripcion: "Porta d'acer inoxidable amb vidre de seguretat", cantidad: 1, unidad: 'ud', precio_unitario: 3000, importe: 3000, es_manuscrito: false, es_partida_alzada: false, element_scope: 'common', unit_hint: null },
      ],
      importe_capitulo: 3000,
    },
  ],
  pem: 5000,
  gastos_generales: { pct: 13, importe: 650 },
  beneficio_industrial: { pct: 6, importe: 300 },
  presupuesto_contrata_sin_iva: 5950,
  iva: { pct: 10, importe: 595 },
  total_con_iva: 6545,
  condiciones_pago: '50 % a l\'acceptació, 50 % a la finalització',
  forma_pago: 'transferencia',
  plazo_ejecucion: '3 setmanes',
  exclusiones: ['Llicència municipal', 'Treballs de pintura'],
  firmado_por_comunidad: true,
  firmado_por_comunidad_rol: 'president',
  validez_dias: 30,
  anotaciones_manuscritas: [],
  evidence: [ev('total_con_iva', 0, '6.545,00 €'), ev('pem', 0, '5.000,00'), ev('emisor.nif', 0, CIF_VENDOR)],
  self_checks: { partidas_suman_pem: true, pem_mas_gg_bi_es_contrata: true, contrata_mas_iva_es_total: true, discrepancia_eur: null },
  idioma: 'ca',
  notes: null,
};

export const paginaFixture: PaginaBatch = {
  pages: [
    {
      page_index: 3,
      doc_type: 'factura',
      page_role: 'first',
      issuer_name_hint: 'Instal·lacions Exemple S.L.',
      doc_number_hint: 'F-2024/017',
      date_hint: '2024-03-15',
      page_marker: '1/2',
      language: 'ca',
      legibility: 0.95,
      is_handwritten_mostly: false,
      continues_previous: false,
      continues_previous_confidence: 0.9,
      reason: 'letterhead with invoice number and date; page marker 1/2',
    },
    {
      page_index: 4,
      doc_type: 'factura',
      page_role: 'last',
      issuer_name_hint: 'Instal·lacions Exemple S.L.',
      doc_number_hint: 'F-2024/017',
      date_hint: null,
      page_marker: '2/2',
      language: 'ca',
      legibility: 0.9,
      is_handwritten_mostly: false,
      continues_previous: true,
      continues_previous_confidence: 0.95,
      reason: 'same footer, totals block, page marker 2/2',
    },
  ],
};

/** Deep clone helper for planting errors in fixtures. */
export function clone<T>(v: T): T {
  return structuredClone(v);
}
