/**
 * The line taxonomy of `docs/taxonomy.md`: 43 category codes with the keyword lists used to
 * map an invoice line, quote partida or certification item to a category.
 *
 * The category decides which expected-price layers apply (`C` contract, `B` approved budget,
 * `K` benchmark, `H` own history), which unit a quantity is converted to, and whether the
 * BENCHMARK layer may be used at all. This module is data only; the matching lives in
 * `classify.ts`.
 *
 * The same rows are seeded into `public.benchmark_categories` by
 * `supabase/migrations/0010_m4_extension.sql`; keep the two identical.
 */

/** Expected-price layer a category can feed. */
export type CategoryLayer = 'C' | 'B' | 'K' | 'H';

/** One taxonomy category. */
export interface BenchmarkCategory {
  /** Stable code, e.g. `PAINT_INT`. */
  code: string;
  labelEs: string;
  labelCa: string;
  labelEn: string;
  /** Spanish keywords, as written in the documents (accents and case are normalised on use). */
  keywordsEs: string[];
  /** Catalan keywords. */
  keywordsCa: string[];
  /** Unit the quantity is expected in, or null when the category has no natural unit. */
  unit: string | null;
  /** Layers that may contribute an expectation for this category. */
  layers: CategoryLayer[];
  /**
   * `false` marks the category as non-benchmarkable in v1: the BENCHMARK layer is skipped and
   * the report prints "no comparable benchmark". CONTRACT and BUDGET still apply.
   */
  comparableDefault: boolean;
  /** Neutral note on comparability or on how the category is handled. */
  notes: string | null;
}

/** The 43 categories, in the order of `docs/taxonomy.md` §1. */
export const CATEGORIES: readonly BenchmarkCategory[] = Object.freeze([
  {
    code: 'ELEV_INSTALL',
    labelEs: 'Instalación de ascensor (equipo)',
    labelCa: "Instal·lació d'ascensor (equip)",
    labelEn: 'Lift installation (equipment)',
    keywordsEs: ['instalación ascensor', 'elevador', 'montaje', 'cabina', 'maquinaria', 'paradas'],
    keywordsCa: ['instal·lació ascensor', 'muntatge', 'cabina', 'parades'],
    unit: 'ud',
    layers: ['C', 'B'],
    comparableDefault: false,
    notes:
      'No comparable reference in v1 for a lift inserted into a protected pre-1965 stairwell; CONTRACT and BUDGET layers only.',
  },
  {
    code: 'ELEV_CIVIL',
    labelEs: 'Obra civil de ascensor',
    labelCa: "Obra civil d'ascensor",
    labelEn: 'Lift civil works',
    keywordsEs: [
      'obra civil ascensor',
      'hueco',
      'foso',
      'estructura metálica',
      'cerramiento',
      'recorte forjado',
    ],
    keywordsCa: ['forat', 'fossat', 'estructura metàl·lica', 'tancament', 'retall forjat'],
    unit: 'ud',
    layers: ['C', 'B'],
    comparableDefault: false,
    notes: 'Non-benchmarkable in v1 (see ELEV_INSTALL).',
  },
  {
    code: 'ELEV_MAINT',
    labelEs: 'Mantenimiento de ascensor',
    labelCa: "Manteniment d'ascensor",
    labelEn: 'Lift maintenance',
    keywordsEs: [
      'mantenimiento ascensor',
      'conservación',
      'todo riesgo',
      'semi integral',
      'cuota mensual',
    ],
    keywordsCa: ['manteniment', 'conservació', 'tot risc'],
    unit: 'mes',
    layers: ['C', 'K', 'H'],
    comparableDefault: true,
    notes:
      'Visit periodicity from RD 355/2024 (ITC AEM 1) drives the expected number of invoices per year.',
  },
  {
    code: 'ELEV_INSPECT',
    labelEs: 'Inspección periódica de ascensor',
    labelCa: "Inspecció periòdica d'ascensor",
    labelEn: 'Lift periodic inspection',
    keywordsEs: ['inspección periódica', 'OCA', 'organismo de control', 'revisión reglamentaria'],
    keywordsCa: ['inspecció periòdica', 'organisme de control'],
    unit: 'ud',
    layers: ['K', 'H'],
    comparableDefault: true,
    notes: 'Paid to the inspection body, not to the maintainer.',
  },
  {
    code: 'ELEV_TELECOM',
    labelEs: 'Línea telefónica de ascensor',
    labelCa: "Línia telefònica d'ascensor",
    labelEn: 'Lift phone / GSM line',
    keywordsEs: ['línea telefónica ascensor', 'GSM', 'telealarma', 'rescate'],
    keywordsCa: ['línia telefònica', 'telealarma', 'rescat'],
    unit: 'mes',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'FACADE_REHAB',
    labelEs: 'Rehabilitación de fachada',
    labelCa: 'Rehabilitació de façana',
    labelEn: 'Façade rehabilitation',
    keywordsEs: ['fachada', 'revoco', 'estuco', 'grietas', 'hidrofugante', 'pintura exterior'],
    keywordsCa: ['façana', 'arrebossat', 'estuc', 'esquerdes', 'hidrofugant'],
    unit: 'm2',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: 'Heritage conditions and rear-façade access widen the band.',
  },
  {
    code: 'BALCONY',
    labelEs: 'Balcones: losa y barandilla',
    labelCa: 'Balcons: llosa i barana',
    labelEn: 'Balcony slab and railing',
    keywordsEs: ['balcón', 'losa', 'canto forjado', 'voladizo', 'barandilla', 'armadura'],
    keywordsCa: ['balcó', 'cantell', 'volada', 'barana', 'armadura'],
    unit: 'ml',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'SCAFFOLD',
    labelEs: 'Andamios',
    labelCa: 'Bastides',
    labelEn: 'Scaffolding',
    keywordsEs: [
      'andamio',
      'montaje y desmontaje',
      'alquiler mensual',
      'ocupación vía pública',
      'lona',
    ],
    keywordsCa: ['bastida', 'muntatge', 'lloguer', 'lona'],
    unit: 'm2·mes',
    layers: ['C', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'ROOF',
    labelEs: 'Cubierta o terrado',
    labelCa: 'Coberta o terrat',
    labelEn: 'Roof / terrace',
    keywordsEs: [
      'cubierta',
      'terrado',
      'azotea',
      'impermeabilización',
      'tela asfáltica',
      'claraboya',
      'lucernario',
    ],
    keywordsCa: ['coberta', 'terrat', 'impermeabilització', 'claraboia'],
    unit: 'm2',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'STAIR_REHAB',
    labelEs: 'Rehabilitación de escalera',
    labelCa: "Rehabilitació d'escala",
    labelEn: 'Staircase rehabilitation',
    keywordsEs: ['escalera', 'peldaños', 'huella', 'pasamanos', 'barandilla', 'mármol', 'terrazo'],
    keywordsCa: ['escala', 'graons', 'passamà', 'barana', 'marbre', 'terratzo'],
    unit: 'ud',
    layers: ['C', 'B'],
    comparableDefault: false,
    notes: 'Non-benchmarkable in v1 for a protected pre-1965 stairwell.',
  },
  {
    code: 'PAINT_INT',
    labelEs: 'Pintura interior de zonas comunes',
    labelCa: 'Pintura interior de zones comunes',
    labelEn: 'Interior painting (common areas)',
    keywordsEs: ['pintura', 'pintar', 'plástica', 'esmalte', 'vestíbulo', 'rellano', 'techos'],
    keywordsCa: ['pintura', 'pintar', 'vestíbul', 'replà', 'sostres'],
    unit: 'm2',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'ENTRANCE_DOOR',
    labelEs: 'Puerta de entrada',
    labelCa: "Porta d'entrada",
    labelEn: 'Entrance door',
    keywordsEs: [
      'puerta entrada',
      'portal',
      'puerta acceso',
      'cierrapuertas',
      'muelle',
      'cerradura',
    ],
    keywordsCa: ["porta d'entrada", 'portal', 'tancaportes', 'pany'],
    unit: 'ud',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: 'A protected ensemble may require restoration instead of replacement.',
  },
  {
    code: 'INTERCOM',
    labelEs: 'Videoportero o portero automático',
    labelCa: 'Videoporter o porter electrònic',
    labelEn: 'Video-entry / intercom',
    keywordsEs: ['videoportero', 'portero automático', 'placa de calle', 'monitor', 'telefonillo'],
    keywordsCa: ['videoporter', 'porter electrònic', 'placa de carrer', 'monitor'],
    unit: 'ud',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: 'Check element_scope: the same words describe private-unit works.',
  },
  {
    code: 'WINDOWS',
    labelEs: 'Ventanas de elementos comunes',
    labelCa: "Finestres d'elements comuns",
    labelEn: 'Windows (common elements)',
    keywordsEs: ['ventana', 'carpintería aluminio', 'RPT', 'vidrio', 'climalit', 'persiana'],
    keywordsCa: ['finestra', "fusteria d'alumini", 'vidre', 'persiana'],
    unit: 'ud',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: 'Check element_scope (rule C11).',
  },
  {
    code: 'LOCKSMITH',
    labelEs: 'Cerrajería',
    labelCa: 'Serralleria',
    labelEn: 'Locksmith',
    keywordsEs: ['cerrajería', 'llaves', 'amaestramiento', 'copias', 'bombín'],
    keywordsCa: ['serralleria', 'claus', 'còpies', 'bombí'],
    unit: 'ud',
    layers: ['K', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'ELECTRICAL',
    labelEs: 'Instalación eléctrica e iluminación menor',
    labelCa: 'Instal·lació elèctrica i enllumenat menor',
    labelEn: 'Electrical installation and minor lighting',
    keywordsEs: [
      'instalación eléctrica',
      'cuadro',
      'luminaria',
      'LED',
      'detector',
      'emergencia',
      'boletín',
      'bombilla',
      'fluorescente',
      'temporizador',
    ],
    keywordsCa: [
      'instal·lació elèctrica',
      'quadre',
      'lluminària',
      'detector',
      'emergència',
      'butlletí',
      'bombeta',
      'fluorescent',
      'temporitzador',
    ],
    unit: 'ud',
    layers: ['C', 'H', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'PLUMB_SEWER',
    labelEs: 'Saneamiento, bajantes y desagües',
    labelCa: 'Sanejament, baixants i desguassos',
    labelEn: 'Sewer, downpipes, drains',
    keywordsEs: [
      'colector',
      'bajante',
      'albañal',
      'desatasco',
      'arqueta',
      'saneamiento',
      'alcantarillado',
      'cámara',
    ],
    keywordsCa: [
      'col·lector',
      'baixant',
      'clavegueró',
      'desembús',
      'arqueta',
      'sanejament',
      'càmera',
    ],
    unit: 'ml',
    layers: ['C', 'B', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'WATER_SUPPLY',
    labelEs: 'Instalación de agua',
    labelCa: "Instal·lació d'aigua",
    labelEn: 'Water supply installation',
    keywordsEs: ['tubería agua', 'batería contadores', 'grupo presión', 'montante', 'fuga'],
    keywordsCa: [
      "canonada d'aigua",
      'bateria de comptadors',
      'grup de pressió',
      'muntant',
      'fuita',
    ],
    unit: 'ud',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'MASONRY',
    labelEs: 'Albañilería y obra menor',
    labelCa: 'Paleteria i obra menor',
    labelEn: 'Masonry and minor works',
    keywordsEs: ['albañilería', 'obra menor', 'reparación', 'humedades', 'yeso', 'tabique'],
    keywordsCa: ['paleteria', 'obra menor', 'reparació', 'humitats', 'guix', 'envà'],
    unit: 'm2',
    layers: ['C', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'ARCH_PROJECT',
    labelEs: 'Proyecto de arquitectura',
    labelCa: "Projecte d'arquitectura",
    labelEn: 'Architect project',
    keywordsEs: ['proyecto básico y ejecución', 'memoria', 'planos', 'visado', 'arquitecto'],
    keywordsCa: ["projecte bàsic i d'execució", 'memòria', 'plànols', 'visat', 'arquitecte'],
    unit: '% PEM',
    layers: ['C', 'K'],
    comparableDefault: true,
    notes: 'Reference fee scales were abolished; the trade ratio supports severity 1 only.',
  },
  {
    code: 'ARCH_DO',
    labelEs: 'Dirección de obra',
    labelCa: "Direcció d'obra",
    labelEn: 'Site direction',
    keywordsEs: [
      'dirección de obra',
      'dirección de ejecución',
      'aparejador',
      'certificación',
      'visita de obra',
    ],
    keywordsCa: [
      "direcció d'obra",
      "direcció d'execució",
      'aparellador',
      'certificació',
      "visita d'obra",
    ],
    unit: '% PEM',
    layers: ['C', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'HS_COORD',
    labelEs: 'Coordinación de seguridad y salud',
    labelCa: 'Coordinació de seguretat i salut',
    labelEn: 'Health and safety coordination',
    keywordsEs: ['coordinación seguridad y salud', 'estudio básico', 'plan de seguridad'],
    keywordsCa: ['coordinació de seguretat i salut', 'estudi bàsic', 'pla de seguretat'],
    unit: '% PEM',
    layers: ['C', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'ITE',
    labelEs: 'Inspección técnica del edificio',
    labelCa: "Inspecció tècnica de l'edifici",
    labelEn: 'Technical building inspection',
    keywordsEs: ['inspección técnica edificio', 'ITE', 'IITE', 'certificado aptitud'],
    keywordsCa: ["inspecció tècnica de l'edifici", 'ITE', 'IITE', 'certificat aptitud'],
    unit: 'ud',
    layers: ['K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'PERMITS',
    labelEs: 'Licencias y tasas municipales',
    labelCa: 'Llicències i taxes municipals',
    labelEn: 'Municipal permits and taxes',
    keywordsEs: [
      'licencia',
      'comunicado',
      'ICIO',
      'tasa',
      'autoliquidación',
      'Ajuntament',
      'ocupación vía pública',
    ],
    keywordsCa: [
      'llicència',
      'comunicat',
      'ICIO',
      'taxa',
      'autoliquidació',
      'Ajuntament',
      'ocupació via pública',
    ],
    unit: '% PEM',
    layers: ['K'],
    comparableDefault: true,
    notes: 'Official tier: municipal fiscal ordinances 2.1 and 3.3, edition by year.',
  },
  {
    code: 'SUBSIDY',
    labelEs: 'Subvenciones: gestión e ingresos',
    labelCa: 'Subvencions: gestió i ingressos',
    labelEn: 'Subsidy processing and income',
    keywordsEs: ['subvención', 'Consorci', 'ayudas', 'gestión expediente', 'informe'],
    keywordsCa: ['subvenció', 'Consorci', 'ajuts', "gestió d'expedient"],
    unit: '% eligible',
    layers: ['B', 'K'],
    comparableDefault: true,
    notes: 'Official tier: the call caps are absolute amounts, not unit prices.',
  },
  {
    code: 'ADMIN_FEE',
    labelEs: 'Honorarios de administración',
    labelCa: "Honoraris d'administració",
    labelEn: 'Administrator fees',
    keywordsEs: ['honorarios administración', 'cuota administración', 'gestión'],
    keywordsCa: ["honoraris d'administració", "quota d'administració", 'gestió'],
    unit: '€/unit·mes',
    layers: ['C', 'H', 'K'],
    comparableDefault: true,
    notes: 'Research packs disagree on the Barcelona range; severity capped at 2 (rule D9).',
  },
  {
    code: 'ADMIN_EXTRA',
    labelEs: 'Extras de administración',
    labelCa: "Extres d'administració",
    labelEn: 'Administrator extras',
    keywordsEs: [
      'junta extraordinaria',
      'certificado deuda',
      'convocatoria',
      'burofax',
      'fotocopias',
      'correo',
    ],
    keywordsCa: [
      'junta extraordinària',
      'certificat de deute',
      'convocatòria',
      'burofax',
      'fotocòpies',
      'correu',
    ],
    unit: 'ud',
    layers: ['C', 'H', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'INSURANCE',
    labelEs: 'Seguro de la comunidad',
    labelCa: 'Assegurança de la comunitat',
    labelEn: 'Community insurance',
    keywordsEs: ['seguro', 'póliza', 'prima', 'recibo', 'siniestro', 'franquicia'],
    keywordsCa: ['assegurança', 'pòlissa', 'prima', 'rebut', 'sinistre', 'franquícia'],
    unit: 'any',
    layers: ['C', 'H', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'CLEANING',
    labelEs: 'Limpieza',
    labelCa: 'Neteja',
    labelEn: 'Cleaning',
    keywordsEs: ['limpieza', 'escalera', 'portal', 'cristales'],
    keywordsCa: ['neteja', 'escala', 'portal', 'vidres'],
    unit: 'mes',
    layers: ['C', 'H', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'ELECTRICITY',
    labelEs: 'Suministro eléctrico',
    labelCa: 'Subministrament elèctric',
    labelEn: 'Electricity utility',
    keywordsEs: ['electricidad', 'luz', 'kWh', 'potencia', 'término fijo'],
    keywordsCa: ['electricitat', 'llum', 'kWh', 'potència', 'terme fix'],
    unit: 'mes',
    layers: ['H'],
    comparableDefault: true,
    notes: 'Benchmark on kWh and tariff, not on an indexed euro amount.',
  },
  {
    code: 'WATER_UTIL',
    labelEs: 'Suministro de agua',
    labelCa: "Subministrament d'aigua",
    labelEn: 'Water utility',
    keywordsEs: ['agua', 'm3', 'canon', 'consumo'],
    keywordsCa: ['aigua', 'm3', 'cànon', 'consum'],
    unit: 'm3',
    layers: ['H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'CAE_PRL',
    labelEs: 'Coordinación de actividades empresariales y PRL',
    labelCa: "Coordinació d'activitats empresarials i PRL",
    labelEn: 'Contractor coordination / risk prevention',
    keywordsEs: [
      'coordinación actividades empresariales',
      'CAE',
      'PRL',
      'prevención riesgos',
      'plataforma',
    ],
    keywordsCa: ["coordinació d'activitats empresarials", 'CAE', 'PRL', 'prevenció de riscos'],
    unit: 'any',
    layers: ['C', 'H', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'LEGAL',
    labelEs: 'Servicios jurídicos y notariales',
    labelCa: 'Serveis jurídics i notarials',
    labelEn: 'Legal and notarial',
    keywordsEs: [
      'abogado',
      'procurador',
      'demanda',
      'reclamación',
      'morosos',
      'notaría',
      'registro',
    ],
    keywordsCa: [
      'advocat',
      'procurador',
      'demanda',
      'reclamació',
      'morosos',
      'notaria',
      'registre',
    ],
    unit: 'h',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'BANK',
    labelEs: 'Comisiones bancarias y servicio de préstamo',
    labelCa: 'Comissions bancàries i servei de préstec',
    labelEn: 'Bank fees and loan service',
    keywordsEs: [
      'comisión',
      'mantenimiento cuenta',
      'transferencia',
      'préstamo',
      'interés',
      'amortización',
      'aval',
    ],
    keywordsCa: [
      'comissió',
      'manteniment de compte',
      'transferència',
      'préstec',
      'interès',
      'amortització',
      'aval',
    ],
    unit: 'mes',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'WASTE',
    labelEs: 'Residuos y contenedores',
    labelCa: 'Residus i contenidors',
    labelEn: 'Waste and containers',
    keywordsEs: ['contenedor', 'escombros', 'saca', 'gestión residuos', 'vertedero'],
    keywordsCa: ['contenidor', 'runa', 'saca', 'gestió de residus', 'abocador'],
    unit: 'ud',
    layers: ['C', 'K'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'PEST',
    labelEs: 'Control de plagas',
    labelCa: 'Control de plagues',
    labelEn: 'Pest control',
    keywordsEs: ['desinsectación', 'desratización', 'plagas'],
    keywordsCa: ['desinsectació', 'desratització', 'plagues'],
    unit: 'ud',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'FIRE',
    labelEs: 'Protección contra incendios',
    labelCa: 'Protecció contra incendis',
    labelEn: 'Fire safety',
    keywordsEs: ['extintor', 'retimbrado', 'BIE', 'señalización'],
    keywordsCa: ['extintor', 'retimbrat', 'BIE', 'senyalització'],
    unit: 'ud',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'TELECOM',
    labelEs: 'Antena y telecomunicaciones',
    labelCa: 'Antena i telecomunicacions',
    labelEn: 'Aerial and telecoms',
    keywordsEs: ['antena', 'TDT', 'amplificador', 'fibra', 'ICT'],
    keywordsCa: ['antena', 'TDT', 'amplificador', 'fibra', 'ICT'],
    unit: 'ud',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'GAS',
    labelEs: 'Instalación de gas',
    labelCa: 'Instal·lació de gas',
    labelEn: 'Gas installation',
    keywordsEs: ['gas', 'revisión', 'instalación receptora'],
    keywordsCa: ['gas', 'revisió', 'instal·lació receptora'],
    unit: 'ud',
    layers: ['C', 'H'],
    comparableDefault: true,
    notes: null,
  },
  {
    code: 'FUND_RESERVE',
    labelEs: 'Fondo de reserva',
    labelCa: 'Fons de reserva',
    labelEn: 'Reserve fund',
    keywordsEs: ['fondo de reserva', 'dotación'],
    keywordsCa: ['fons de reserva', 'dotació'],
    unit: 'any',
    layers: ['B'],
    comparableDefault: true,
    notes: 'Budget layer only: at least 5% of the ordinary budget (CCCat 553-6, to verify).',
  },
  {
    code: 'DERRAMA',
    labelEs: 'Derrama o cuota extraordinaria',
    labelCa: 'Derrama o quota extraordinària',
    labelEn: 'Extraordinary contribution',
    keywordsEs: ['derrama', 'cuota extraordinaria', 'aportación obras'],
    keywordsCa: ['derrama', 'quota extraordinària', 'aportació obres'],
    unit: 'unit·mes',
    layers: ['B'],
    comparableDefault: true,
    notes: 'Expectation computed by D5/D5b, not by a price benchmark.',
  },
  {
    code: 'MISC',
    labelEs: 'Sin clasificar',
    labelCa: 'Sense classificar',
    labelEn: 'Unclassified',
    keywordsEs: ['varios', 'otros', 'imprevistos', 'material', 'ferretería'],
    keywordsCa: ['altres', 'imprevistos', 'material', 'ferreteria'],
    unit: null,
    layers: [],
    comparableDefault: false,
    notes: 'Goes to the review queue; no layer applies until reclassified.',
  },
  {
    code: 'ASBESTOS',
    labelEs: 'Retirada de amianto',
    labelCa: "Retirada d'amiant",
    labelEn: 'Asbestos removal',
    keywordsEs: ['amianto', 'uralita', 'fibrocemento', 'desamiantado', 'plan de trabajo'],
    keywordsCa: ['amiant', 'uralita', 'fibrociment', 'desamiantat', 'pla de treball'],
    unit: 'ml',
    layers: ['C', 'K'],
    comparableDefault: true,
    notes: 'Registry check under rules G5/G6.',
  },
]);

/** Every category code, in taxonomy order. */
export const CATEGORY_CODES: readonly string[] = Object.freeze(CATEGORIES.map((c) => c.code));

const BY_CODE = new Map<string, BenchmarkCategory>(CATEGORIES.map((c) => [c.code, c]));

/** Category for a code, or undefined when the code is unknown. */
export function categoryByCode(code: string | null | undefined): BenchmarkCategory | undefined {
  return code ? BY_CODE.get(code) : undefined;
}

/** Code used when no keyword matches and no vendor memory applies. */
export const UNCLASSIFIED_CODE = 'MISC';

/**
 * Categories with no comparable reference in v1. The BENCHMARK layer is skipped for these and
 * the expected price rests on the contract and budget layers only.
 */
export const NON_BENCHMARKABLE_CODES: ReadonlySet<string> = Object.freeze(
  new Set(CATEGORIES.filter((c) => !c.comparableDefault).map((c) => c.code)),
);

/** Whether a category may enter the BENCHMARK layer at all. */
export function isBenchmarkable(code: string | null | undefined): boolean {
  const cat = categoryByCode(code);
  return cat ? cat.comparableDefault && cat.layers.includes('K') : false;
}

/** Whether a category may use a layer. */
export function hasLayer(code: string | null | undefined, layer: CategoryLayer): boolean {
  return categoryByCode(code)?.layers.includes(layer) ?? false;
}
